services:
  postgres:
    image: postgres:16-alpine
    container_name: agendafacil-postgres
    environment:
      POSTGRES_DB: agendafacil_pro
      POSTGRES_USER: agendafacil
      POSTGRES_PASSWORD: ${DB_PASSWORD:?Defina DB_PASSWORD no arquivo .env}
      TZ: ${APP_TIME_ZONE:-America/Sao_Paulo}
      PGTZ: ${APP_TIME_ZONE:-America/Sao_Paulo}
    ports:
      - "5432:5432"
    volumes:
      - agendafacil_pg:/var/lib/postgresql/data

volumes:
  agendafacil_pg:
