spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/agendafacil_pro}
    username: ${DB_USERNAME:agendafacil}
    password: ${DB_PASSWORD:}
    hikari:
      connection-init-sql: SET TIME ZONE '${APP_TIME_ZONE:America/Sao_Paulo}'
  thymeleaf:
    cache: false

app:
  time-zone: ${APP_TIME_ZONE:America/Sao_Paulo}

server:
  servlet:
    session:
      cookie:
        secure: false
