spring:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  thymeleaf:
    cache: true

app:
  provisioning:
    enabled: false

server:
  servlet:
    session:
      timeout: 30m
      cookie:
        name: AGENDAFACIL_SESSION
        http-only: true
        secure: true
        same-site: strict
  error:
    whitelabel:
      enabled: false
    include-message: never
    include-stacktrace: never
    include-binding-errors: never
