spring:
  datasource:
    url: ${DB_URL:}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
    hikari:
      connection-init-sql: SET TIME ZONE '${APP_TIME_ZONE:}'
  thymeleaf:
    cache: true

app:
  time-zone: ${APP_TIME_ZONE:}
  provisioning:
    enabled: false

server:
  address: 127.0.0.1
  forward-headers-strategy: native
  tomcat:
    redirect-context-root: false
    remoteip:
      remote-ip-header: X-Forwarded-For
      protocol-header: X-Forwarded-Proto
      host-header: X-Forwarded-Host
      internal-proxies: 127.0.0.1/32
  servlet:
    session:
      cookie:
        secure: true
